Started GET "/members" for ::1 at 2022-01-28 12:29:55 -0500
  [1m[35m (1.9ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
Processing by MembersController#index as HTML
  [1m[36mMember Load (4.8ms)[0m  [1m[34mSELECT "members".* FROM "members"[0m
  â†³ app/controllers/members_controller.rb:7:in `index'
No serializer found for resource: #<Member id: 14, first_name: "Madison", last_name: "Sorah", username: "mochipancake", email: "madisonsorah@gmail.com", password_digest: [FILTERED], bio: "Hi there! I am a cat lover, anime watcher and fron...", avatar_url: "XX", created_at: "2022-01-28 17:02:53.697097000 +0000", updated_at: "2022-01-28 17:02:53.697097000 +0000">
[active_model_serializers] Rendered ActiveModel::Serializer::CollectionSerializer with Member::ActiveRecord_Relation (0.48ms)
Completed 200 OK in 31ms (Views: 10.5ms | ActiveRecord: 11.0ms | Allocations: 11593)


Started GET "/created_playlists" for ::1 at 2022-01-28 12:30:02 -0500
Processing by CreatedPlaylistsController#index as HTML
  [1m[36mPlaylist Load (5.4ms)[0m  [1m[34mSELECT "playlists".* FROM "playlists" WHERE "playlists"."creator_id" IS NOT NULL[0m
  â†³ app/controllers/created_playlists_controller.rb:7:in `index'
No serializer found for resource: #<Playlist id: 14, title: "XX", cover_url: "XX", playlist_url: "XX", description: "Looking for a playlist with soft, dreamy vibes.", requester_id: 14, creator_id: 15, created_at: "2022-01-28 17:02:53.982940000 +0000", updated_at: "2022-01-28 17:02:53.982940000 +0000">
[active_model_serializers] Rendered ActiveModel::Serializer::CollectionSerializer with Playlist::ActiveRecord_Relation (0.6ms)
Completed 200 OK in 34ms (Views: 16.0ms | ActiveRecord: 10.0ms | Allocations: 6850)


Started GET "/hello" for 127.0.0.1 at 2022-01-28 12:33:44 -0500
Processing by ApplicationController#hello_world as */*
[active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.12ms)
Completed 200 OK in 21ms (Views: 10.2ms | ActiveRecord: 0.0ms | Allocations: 2484)


Started GET "/hello" for 127.0.0.1 at 2022-01-28 12:44:02 -0500
  
ActiveRecord::ConnectionNotEstablished (could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
):
  
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:83:in `rescue in new_client'
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:77:in `new_client'
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `public_send'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:926:in `checkout_new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:905:in `try_to_checkout_new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:866:in `acquire_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:588:in `checkout'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:428:in `connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:1128:in `retrieve_connection'
activerecord (6.1.4.4) lib/active_record/connection_handling.rb:327:in `retrieve_connection'
activerecord (6.1.4.4) lib/active_record/connection_handling.rb:283:in `connection'
activerecord (6.1.4.4) lib/active_record/migration.rb:611:in `connection'
activerecord (6.1.4.4) lib/active_record/migration.rb:606:in `build_watcher'
activerecord (6.1.4.4) lib/active_record/migration.rb:588:in `block in call'
activerecord (6.1.4.4) lib/active_record/migration.rb:587:in `synchronize'
activerecord (6.1.4.4) lib/active_record/migration.rb:587:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.1.4.4) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (6.1.4.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.1.4.4) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.1.4.4) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (6.1.4.4) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.1.4.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/static.rb:24:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/host_authorization.rb:119:in `call'
railties (6.1.4.4) lib/rails/engine.rb:539:in `call'
puma (5.5.2) lib/puma/configuration.rb:249:in `call'
puma (5.5.2) lib/puma/request.rb:77:in `block in handle_request'
puma (5.5.2) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
puma (5.5.2) lib/puma/request.rb:76:in `handle_request'
puma (5.5.2) lib/puma/server.rb:447:in `process_client'
puma (5.5.2) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
Started GET "/hello" for 127.0.0.1 at 2022-01-28 12:44:15 -0500
  
ActiveRecord::ConnectionNotEstablished (could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
):
  
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:83:in `rescue in new_client'
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:77:in `new_client'
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `public_send'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:926:in `checkout_new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:905:in `try_to_checkout_new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:866:in `acquire_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:588:in `checkout'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:428:in `connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:1128:in `retrieve_connection'
activerecord (6.1.4.4) lib/active_record/connection_handling.rb:327:in `retrieve_connection'
activerecord (6.1.4.4) lib/active_record/connection_handling.rb:283:in `connection'
activerecord (6.1.4.4) lib/active_record/migration.rb:611:in `connection'
activerecord (6.1.4.4) lib/active_record/migration.rb:606:in `build_watcher'
activerecord (6.1.4.4) lib/active_record/migration.rb:588:in `block in call'
activerecord (6.1.4.4) lib/active_record/migration.rb:587:in `synchronize'
activerecord (6.1.4.4) lib/active_record/migration.rb:587:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.1.4.4) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (6.1.4.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.1.4.4) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.1.4.4) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (6.1.4.4) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.1.4.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/static.rb:24:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/host_authorization.rb:119:in `call'
railties (6.1.4.4) lib/rails/engine.rb:539:in `call'
puma (5.5.2) lib/puma/configuration.rb:249:in `call'
puma (5.5.2) lib/puma/request.rb:77:in `block in handle_request'
puma (5.5.2) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
puma (5.5.2) lib/puma/request.rb:76:in `handle_request'
puma (5.5.2) lib/puma/server.rb:447:in `process_client'
puma (5.5.2) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
Started GET "/hello" for 127.0.0.1 at 2022-01-28 12:44:16 -0500
  
ActiveRecord::ConnectionNotEstablished (could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
):
  
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:83:in `rescue in new_client'
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:77:in `new_client'
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `public_send'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:926:in `checkout_new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:905:in `try_to_checkout_new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:866:in `acquire_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:588:in `checkout'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:428:in `connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:1128:in `retrieve_connection'
activerecord (6.1.4.4) lib/active_record/connection_handling.rb:327:in `retrieve_connection'
activerecord (6.1.4.4) lib/active_record/connection_handling.rb:283:in `connection'
activerecord (6.1.4.4) lib/active_record/migration.rb:611:in `connection'
activerecord (6.1.4.4) lib/active_record/migration.rb:606:in `build_watcher'
activerecord (6.1.4.4) lib/active_record/migration.rb:588:in `block in call'
activerecord (6.1.4.4) lib/active_record/migration.rb:587:in `synchronize'
activerecord (6.1.4.4) lib/active_record/migration.rb:587:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.1.4.4) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (6.1.4.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.1.4.4) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.1.4.4) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (6.1.4.4) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.1.4.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/static.rb:24:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/host_authorization.rb:119:in `call'
railties (6.1.4.4) lib/rails/engine.rb:539:in `call'
puma (5.5.2) lib/puma/configuration.rb:249:in `call'
puma (5.5.2) lib/puma/request.rb:77:in `block in handle_request'
puma (5.5.2) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
puma (5.5.2) lib/puma/request.rb:76:in `handle_request'
puma (5.5.2) lib/puma/server.rb:447:in `process_client'
puma (5.5.2) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
Started GET "/hello" for 127.0.0.1 at 2022-01-28 12:44:18 -0500
  
ActiveRecord::ConnectionNotEstablished (could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
):
  
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:83:in `rescue in new_client'
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:77:in `new_client'
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `public_send'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:926:in `checkout_new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:905:in `try_to_checkout_new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:866:in `acquire_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:588:in `checkout'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:428:in `connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:1128:in `retrieve_connection'
activerecord (6.1.4.4) lib/active_record/connection_handling.rb:327:in `retrieve_connection'
activerecord (6.1.4.4) lib/active_record/connection_handling.rb:283:in `connection'
activerecord (6.1.4.4) lib/active_record/migration.rb:611:in `connection'
activerecord (6.1.4.4) lib/active_record/migration.rb:606:in `build_watcher'
activerecord (6.1.4.4) lib/active_record/migration.rb:588:in `block in call'
activerecord (6.1.4.4) lib/active_record/migration.rb:587:in `synchronize'
activerecord (6.1.4.4) lib/active_record/migration.rb:587:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.1.4.4) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (6.1.4.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.1.4.4) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.1.4.4) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (6.1.4.4) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.1.4.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/static.rb:24:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/host_authorization.rb:119:in `call'
railties (6.1.4.4) lib/rails/engine.rb:539:in `call'
puma (5.5.2) lib/puma/configuration.rb:249:in `call'
puma (5.5.2) lib/puma/request.rb:77:in `block in handle_request'
puma (5.5.2) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
puma (5.5.2) lib/puma/request.rb:76:in `handle_request'
puma (5.5.2) lib/puma/server.rb:447:in `process_client'
puma (5.5.2) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
Started GET "/hello" for 127.0.0.1 at 2022-01-28 12:44:19 -0500
  
ActiveRecord::ConnectionNotEstablished (could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
):
  
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:83:in `rescue in new_client'
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:77:in `new_client'
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `public_send'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:926:in `checkout_new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:905:in `try_to_checkout_new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:866:in `acquire_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:588:in `checkout'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:428:in `connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:1128:in `retrieve_connection'
activerecord (6.1.4.4) lib/active_record/connection_handling.rb:327:in `retrieve_connection'
activerecord (6.1.4.4) lib/active_record/connection_handling.rb:283:in `connection'
activerecord (6.1.4.4) lib/active_record/migration.rb:611:in `connection'
activerecord (6.1.4.4) lib/active_record/migration.rb:606:in `build_watcher'
activerecord (6.1.4.4) lib/active_record/migration.rb:588:in `block in call'
activerecord (6.1.4.4) lib/active_record/migration.rb:587:in `synchronize'
activerecord (6.1.4.4) lib/active_record/migration.rb:587:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.1.4.4) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (6.1.4.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.1.4.4) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.1.4.4) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (6.1.4.4) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.1.4.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/static.rb:24:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/host_authorization.rb:119:in `call'
railties (6.1.4.4) lib/rails/engine.rb:539:in `call'
puma (5.5.2) lib/puma/configuration.rb:249:in `call'
puma (5.5.2) lib/puma/request.rb:77:in `block in handle_request'
puma (5.5.2) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
puma (5.5.2) lib/puma/request.rb:76:in `handle_request'
puma (5.5.2) lib/puma/server.rb:447:in `process_client'
puma (5.5.2) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
Started GET "/hello" for 127.0.0.1 at 2022-01-28 12:44:20 -0500
  
ActiveRecord::ConnectionNotEstablished (could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
):
  
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:83:in `rescue in new_client'
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:77:in `new_client'
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `public_send'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:926:in `checkout_new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:905:in `try_to_checkout_new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:866:in `acquire_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:588:in `checkout'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:428:in `connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:1128:in `retrieve_connection'
activerecord (6.1.4.4) lib/active_record/connection_handling.rb:327:in `retrieve_connection'
activerecord (6.1.4.4) lib/active_record/connection_handling.rb:283:in `connection'
activerecord (6.1.4.4) lib/active_record/migration.rb:611:in `connection'
activerecord (6.1.4.4) lib/active_record/migration.rb:606:in `build_watcher'
activerecord (6.1.4.4) lib/active_record/migration.rb:588:in `block in call'
activerecord (6.1.4.4) lib/active_record/migration.rb:587:in `synchronize'
activerecord (6.1.4.4) lib/active_record/migration.rb:587:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.1.4.4) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (6.1.4.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.1.4.4) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.1.4.4) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (6.1.4.4) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.1.4.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/static.rb:24:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/host_authorization.rb:119:in `call'
railties (6.1.4.4) lib/rails/engine.rb:539:in `call'
puma (5.5.2) lib/puma/configuration.rb:249:in `call'
puma (5.5.2) lib/puma/request.rb:77:in `block in handle_request'
puma (5.5.2) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
puma (5.5.2) lib/puma/request.rb:76:in `handle_request'
puma (5.5.2) lib/puma/server.rb:447:in `process_client'
puma (5.5.2) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
Started GET "/hello" for 127.0.0.1 at 2022-01-28 12:44:22 -0500
  
ActiveRecord::ConnectionNotEstablished (could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
):
  
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:83:in `rescue in new_client'
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:77:in `new_client'
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `public_send'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:926:in `checkout_new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:905:in `try_to_checkout_new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:866:in `acquire_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:588:in `checkout'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:428:in `connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:1128:in `retrieve_connection'
activerecord (6.1.4.4) lib/active_record/connection_handling.rb:327:in `retrieve_connection'
activerecord (6.1.4.4) lib/active_record/connection_handling.rb:283:in `connection'
activerecord (6.1.4.4) lib/active_record/migration.rb:611:in `connection'
activerecord (6.1.4.4) lib/active_record/migration.rb:606:in `build_watcher'
activerecord (6.1.4.4) lib/active_record/migration.rb:588:in `block in call'
activerecord (6.1.4.4) lib/active_record/migration.rb:587:in `synchronize'
activerecord (6.1.4.4) lib/active_record/migration.rb:587:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.1.4.4) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (6.1.4.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.1.4.4) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.1.4.4) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (6.1.4.4) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.1.4.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/static.rb:24:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/host_authorization.rb:119:in `call'
railties (6.1.4.4) lib/rails/engine.rb:539:in `call'
puma (5.5.2) lib/puma/configuration.rb:249:in `call'
puma (5.5.2) lib/puma/request.rb:77:in `block in handle_request'
puma (5.5.2) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
puma (5.5.2) lib/puma/request.rb:76:in `handle_request'
puma (5.5.2) lib/puma/server.rb:447:in `process_client'
puma (5.5.2) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
Started GET "/hello" for 127.0.0.1 at 2022-01-28 12:44:22 -0500
  
ActiveRecord::ConnectionNotEstablished (could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
):
  
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:83:in `rescue in new_client'
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:77:in `new_client'
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `public_send'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:926:in `checkout_new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:905:in `try_to_checkout_new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:866:in `acquire_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:588:in `checkout'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:428:in `connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:1128:in `retrieve_connection'
activerecord (6.1.4.4) lib/active_record/connection_handling.rb:327:in `retrieve_connection'
activerecord (6.1.4.4) lib/active_record/connection_handling.rb:283:in `connection'
activerecord (6.1.4.4) lib/active_record/migration.rb:611:in `connection'
activerecord (6.1.4.4) lib/active_record/migration.rb:606:in `build_watcher'
activerecord (6.1.4.4) lib/active_record/migration.rb:588:in `block in call'
activerecord (6.1.4.4) lib/active_record/migration.rb:587:in `synchronize'
activerecord (6.1.4.4) lib/active_record/migration.rb:587:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.1.4.4) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (6.1.4.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.1.4.4) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.1.4.4) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (6.1.4.4) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.1.4.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/static.rb:24:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/host_authorization.rb:119:in `call'
railties (6.1.4.4) lib/rails/engine.rb:539:in `call'
puma (5.5.2) lib/puma/configuration.rb:249:in `call'
puma (5.5.2) lib/puma/request.rb:77:in `block in handle_request'
puma (5.5.2) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
puma (5.5.2) lib/puma/request.rb:76:in `handle_request'
puma (5.5.2) lib/puma/server.rb:447:in `process_client'
puma (5.5.2) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
Started GET "/hello" for 127.0.0.1 at 2022-01-28 12:44:24 -0500
  
ActiveRecord::ConnectionNotEstablished (could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
):
  
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:83:in `rescue in new_client'
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:77:in `new_client'
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `public_send'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:926:in `checkout_new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:905:in `try_to_checkout_new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:866:in `acquire_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:588:in `checkout'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:428:in `connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:1128:in `retrieve_connection'
activerecord (6.1.4.4) lib/active_record/connection_handling.rb:327:in `retrieve_connection'
activerecord (6.1.4.4) lib/active_record/connection_handling.rb:283:in `connection'
activerecord (6.1.4.4) lib/active_record/migration.rb:611:in `connection'
activerecord (6.1.4.4) lib/active_record/migration.rb:606:in `build_watcher'
activerecord (6.1.4.4) lib/active_record/migration.rb:588:in `block in call'
activerecord (6.1.4.4) lib/active_record/migration.rb:587:in `synchronize'
activerecord (6.1.4.4) lib/active_record/migration.rb:587:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.1.4.4) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (6.1.4.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.1.4.4) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.1.4.4) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (6.1.4.4) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.1.4.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/static.rb:24:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/host_authorization.rb:119:in `call'
railties (6.1.4.4) lib/rails/engine.rb:539:in `call'
puma (5.5.2) lib/puma/configuration.rb:249:in `call'
puma (5.5.2) lib/puma/request.rb:77:in `block in handle_request'
puma (5.5.2) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
puma (5.5.2) lib/puma/request.rb:76:in `handle_request'
puma (5.5.2) lib/puma/server.rb:447:in `process_client'
puma (5.5.2) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
Started GET "/hello" for 127.0.0.1 at 2022-01-28 12:46:35 -0500
  
ActiveRecord::ConnectionNotEstablished (could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
):
  
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:83:in `rescue in new_client'
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:77:in `new_client'
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `public_send'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:926:in `checkout_new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:905:in `try_to_checkout_new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:866:in `acquire_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:588:in `checkout'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:428:in `connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:1128:in `retrieve_connection'
activerecord (6.1.4.4) lib/active_record/connection_handling.rb:327:in `retrieve_connection'
activerecord (6.1.4.4) lib/active_record/connection_handling.rb:283:in `connection'
activerecord (6.1.4.4) lib/active_record/migration.rb:611:in `connection'
activerecord (6.1.4.4) lib/active_record/migration.rb:606:in `build_watcher'
activerecord (6.1.4.4) lib/active_record/migration.rb:588:in `block in call'
activerecord (6.1.4.4) lib/active_record/migration.rb:587:in `synchronize'
activerecord (6.1.4.4) lib/active_record/migration.rb:587:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.1.4.4) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (6.1.4.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.1.4.4) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.1.4.4) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (6.1.4.4) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.1.4.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/static.rb:24:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/host_authorization.rb:119:in `call'
railties (6.1.4.4) lib/rails/engine.rb:539:in `call'
puma (5.5.2) lib/puma/configuration.rb:249:in `call'
puma (5.5.2) lib/puma/request.rb:77:in `block in handle_request'
puma (5.5.2) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
puma (5.5.2) lib/puma/request.rb:76:in `handle_request'
puma (5.5.2) lib/puma/server.rb:447:in `process_client'
puma (5.5.2) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
Started GET "/hello" for 127.0.0.1 at 2022-01-28 12:47:05 -0500
  
ActiveRecord::ConnectionNotEstablished (could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
):
  
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:83:in `rescue in new_client'
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:77:in `new_client'
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `public_send'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:926:in `checkout_new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:905:in `try_to_checkout_new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:866:in `acquire_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:588:in `checkout'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:428:in `connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:1128:in `retrieve_connection'
activerecord (6.1.4.4) lib/active_record/connection_handling.rb:327:in `retrieve_connection'
activerecord (6.1.4.4) lib/active_record/connection_handling.rb:283:in `connection'
activerecord (6.1.4.4) lib/active_record/migration.rb:611:in `connection'
activerecord (6.1.4.4) lib/active_record/migration.rb:606:in `build_watcher'
activerecord (6.1.4.4) lib/active_record/migration.rb:588:in `block in call'
activerecord (6.1.4.4) lib/active_record/migration.rb:587:in `synchronize'
activerecord (6.1.4.4) lib/active_record/migration.rb:587:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.1.4.4) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (6.1.4.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.1.4.4) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.1.4.4) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (6.1.4.4) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.1.4.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/static.rb:24:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/host_authorization.rb:119:in `call'
railties (6.1.4.4) lib/rails/engine.rb:539:in `call'
puma (5.5.2) lib/puma/configuration.rb:249:in `call'
puma (5.5.2) lib/puma/request.rb:77:in `block in handle_request'
puma (5.5.2) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
puma (5.5.2) lib/puma/request.rb:76:in `handle_request'
puma (5.5.2) lib/puma/server.rb:447:in `process_client'
puma (5.5.2) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
Started GET "/hello" for 127.0.0.1 at 2022-01-28 12:47:06 -0500
  
ActiveRecord::ConnectionNotEstablished (could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
):
  
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:83:in `rescue in new_client'
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:77:in `new_client'
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `public_send'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:926:in `checkout_new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:905:in `try_to_checkout_new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:866:in `acquire_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:588:in `checkout'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:428:in `connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:1128:in `retrieve_connection'
activerecord (6.1.4.4) lib/active_record/connection_handling.rb:327:in `retrieve_connection'
activerecord (6.1.4.4) lib/active_record/connection_handling.rb:283:in `connection'
activerecord (6.1.4.4) lib/active_record/migration.rb:611:in `connection'
activerecord (6.1.4.4) lib/active_record/migration.rb:606:in `build_watcher'
activerecord (6.1.4.4) lib/active_record/migration.rb:588:in `block in call'
activerecord (6.1.4.4) lib/active_record/migration.rb:587:in `synchronize'
activerecord (6.1.4.4) lib/active_record/migration.rb:587:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.1.4.4) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (6.1.4.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.1.4.4) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.1.4.4) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (6.1.4.4) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.1.4.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/static.rb:24:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/host_authorization.rb:119:in `call'
railties (6.1.4.4) lib/rails/engine.rb:539:in `call'
puma (5.5.2) lib/puma/configuration.rb:249:in `call'
puma (5.5.2) lib/puma/request.rb:77:in `block in handle_request'
puma (5.5.2) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
puma (5.5.2) lib/puma/request.rb:76:in `handle_request'
puma (5.5.2) lib/puma/server.rb:447:in `process_client'
puma (5.5.2) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
Started GET "/hello" for 127.0.0.1 at 2022-01-28 12:47:08 -0500
  
ActiveRecord::ConnectionNotEstablished (could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
):
  
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:83:in `rescue in new_client'
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:77:in `new_client'
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `public_send'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:926:in `checkout_new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:905:in `try_to_checkout_new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:866:in `acquire_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:588:in `checkout'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:428:in `connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:1128:in `retrieve_connection'
activerecord (6.1.4.4) lib/active_record/connection_handling.rb:327:in `retrieve_connection'
activerecord (6.1.4.4) lib/active_record/connection_handling.rb:283:in `connection'
activerecord (6.1.4.4) lib/active_record/migration.rb:611:in `connection'
activerecord (6.1.4.4) lib/active_record/migration.rb:606:in `build_watcher'
activerecord (6.1.4.4) lib/active_record/migration.rb:588:in `block in call'
activerecord (6.1.4.4) lib/active_record/migration.rb:587:in `synchronize'
activerecord (6.1.4.4) lib/active_record/migration.rb:587:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.1.4.4) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (6.1.4.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.1.4.4) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.1.4.4) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (6.1.4.4) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.1.4.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/static.rb:24:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/host_authorization.rb:119:in `call'
railties (6.1.4.4) lib/rails/engine.rb:539:in `call'
puma (5.5.2) lib/puma/configuration.rb:249:in `call'
puma (5.5.2) lib/puma/request.rb:77:in `block in handle_request'
puma (5.5.2) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
puma (5.5.2) lib/puma/request.rb:76:in `handle_request'
puma (5.5.2) lib/puma/server.rb:447:in `process_client'
puma (5.5.2) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
Started GET "/hello" for 127.0.0.1 at 2022-01-28 12:47:09 -0500
  
ActiveRecord::ConnectionNotEstablished (could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
):
  
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:83:in `rescue in new_client'
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:77:in `new_client'
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `public_send'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:926:in `checkout_new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:905:in `try_to_checkout_new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:866:in `acquire_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:588:in `checkout'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:428:in `connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:1128:in `retrieve_connection'
activerecord (6.1.4.4) lib/active_record/connection_handling.rb:327:in `retrieve_connection'
activerecord (6.1.4.4) lib/active_record/connection_handling.rb:283:in `connection'
activerecord (6.1.4.4) lib/active_record/migration.rb:611:in `connection'
activerecord (6.1.4.4) lib/active_record/migration.rb:606:in `build_watcher'
activerecord (6.1.4.4) lib/active_record/migration.rb:588:in `block in call'
activerecord (6.1.4.4) lib/active_record/migration.rb:587:in `synchronize'
activerecord (6.1.4.4) lib/active_record/migration.rb:587:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.1.4.4) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (6.1.4.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.1.4.4) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.1.4.4) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (6.1.4.4) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.1.4.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/static.rb:24:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/host_authorization.rb:119:in `call'
railties (6.1.4.4) lib/rails/engine.rb:539:in `call'
puma (5.5.2) lib/puma/configuration.rb:249:in `call'
puma (5.5.2) lib/puma/request.rb:77:in `block in handle_request'
puma (5.5.2) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
puma (5.5.2) lib/puma/request.rb:76:in `handle_request'
puma (5.5.2) lib/puma/server.rb:447:in `process_client'
puma (5.5.2) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
Started GET "/hello" for 127.0.0.1 at 2022-01-28 12:48:33 -0500
  
ActiveRecord::ConnectionNotEstablished (could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
):
  
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:83:in `rescue in new_client'
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:77:in `new_client'
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `public_send'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:926:in `checkout_new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:905:in `try_to_checkout_new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:866:in `acquire_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:588:in `checkout'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:428:in `connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:1128:in `retrieve_connection'
activerecord (6.1.4.4) lib/active_record/connection_handling.rb:327:in `retrieve_connection'
activerecord (6.1.4.4) lib/active_record/connection_handling.rb:283:in `connection'
activerecord (6.1.4.4) lib/active_record/migration.rb:611:in `connection'
activerecord (6.1.4.4) lib/active_record/migration.rb:606:in `build_watcher'
activerecord (6.1.4.4) lib/active_record/migration.rb:588:in `block in call'
activerecord (6.1.4.4) lib/active_record/migration.rb:587:in `synchronize'
activerecord (6.1.4.4) lib/active_record/migration.rb:587:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.1.4.4) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (6.1.4.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.1.4.4) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.1.4.4) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (6.1.4.4) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.1.4.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/static.rb:24:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/host_authorization.rb:119:in `call'
railties (6.1.4.4) lib/rails/engine.rb:539:in `call'
puma (5.5.2) lib/puma/configuration.rb:249:in `call'
puma (5.5.2) lib/puma/request.rb:77:in `block in handle_request'
puma (5.5.2) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
puma (5.5.2) lib/puma/request.rb:76:in `handle_request'
puma (5.5.2) lib/puma/server.rb:447:in `process_client'
puma (5.5.2) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
Started GET "/hello" for 127.0.0.1 at 2022-01-28 12:48:35 -0500
  
ActiveRecord::ConnectionNotEstablished (could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
):
  
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:83:in `rescue in new_client'
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:77:in `new_client'
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `public_send'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:926:in `checkout_new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:905:in `try_to_checkout_new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:866:in `acquire_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:588:in `checkout'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:428:in `connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:1128:in `retrieve_connection'
activerecord (6.1.4.4) lib/active_record/connection_handling.rb:327:in `retrieve_connection'
activerecord (6.1.4.4) lib/active_record/connection_handling.rb:283:in `connection'
activerecord (6.1.4.4) lib/active_record/migration.rb:611:in `connection'
activerecord (6.1.4.4) lib/active_record/migration.rb:606:in `build_watcher'
activerecord (6.1.4.4) lib/active_record/migration.rb:588:in `block in call'
activerecord (6.1.4.4) lib/active_record/migration.rb:587:in `synchronize'
activerecord (6.1.4.4) lib/active_record/migration.rb:587:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.1.4.4) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (6.1.4.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.1.4.4) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.1.4.4) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (6.1.4.4) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.1.4.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/static.rb:24:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/host_authorization.rb:119:in `call'
railties (6.1.4.4) lib/rails/engine.rb:539:in `call'
puma (5.5.2) lib/puma/configuration.rb:249:in `call'
puma (5.5.2) lib/puma/request.rb:77:in `block in handle_request'
puma (5.5.2) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
puma (5.5.2) lib/puma/request.rb:76:in `handle_request'
puma (5.5.2) lib/puma/server.rb:447:in `process_client'
puma (5.5.2) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
Started GET "/hello" for 127.0.0.1 at 2022-01-28 12:48:36 -0500
  
ActiveRecord::ConnectionNotEstablished (could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
):
  
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:83:in `rescue in new_client'
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:77:in `new_client'
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `public_send'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:926:in `checkout_new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:905:in `try_to_checkout_new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:866:in `acquire_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:588:in `checkout'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:428:in `connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:1128:in `retrieve_connection'
activerecord (6.1.4.4) lib/active_record/connection_handling.rb:327:in `retrieve_connection'
activerecord (6.1.4.4) lib/active_record/connection_handling.rb:283:in `connection'
activerecord (6.1.4.4) lib/active_record/migration.rb:611:in `connection'
activerecord (6.1.4.4) lib/active_record/migration.rb:606:in `build_watcher'
activerecord (6.1.4.4) lib/active_record/migration.rb:588:in `block in call'
activerecord (6.1.4.4) lib/active_record/migration.rb:587:in `synchronize'
activerecord (6.1.4.4) lib/active_record/migration.rb:587:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.1.4.4) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (6.1.4.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.1.4.4) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.1.4.4) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (6.1.4.4) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.1.4.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/static.rb:24:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/host_authorization.rb:119:in `call'
railties (6.1.4.4) lib/rails/engine.rb:539:in `call'
puma (5.5.2) lib/puma/configuration.rb:249:in `call'
puma (5.5.2) lib/puma/request.rb:77:in `block in handle_request'
puma (5.5.2) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
puma (5.5.2) lib/puma/request.rb:76:in `handle_request'
puma (5.5.2) lib/puma/server.rb:447:in `process_client'
puma (5.5.2) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
Started GET "/hello" for 127.0.0.1 at 2022-01-28 12:48:39 -0500
  
ActiveRecord::ConnectionNotEstablished (could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
):
  
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:83:in `rescue in new_client'
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:77:in `new_client'
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `public_send'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:926:in `checkout_new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:905:in `try_to_checkout_new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:866:in `acquire_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:588:in `checkout'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:428:in `connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:1128:in `retrieve_connection'
activerecord (6.1.4.4) lib/active_record/connection_handling.rb:327:in `retrieve_connection'
activerecord (6.1.4.4) lib/active_record/connection_handling.rb:283:in `connection'
activerecord (6.1.4.4) lib/active_record/migration.rb:611:in `connection'
activerecord (6.1.4.4) lib/active_record/migration.rb:606:in `build_watcher'
activerecord (6.1.4.4) lib/active_record/migration.rb:588:in `block in call'
activerecord (6.1.4.4) lib/active_record/migration.rb:587:in `synchronize'
activerecord (6.1.4.4) lib/active_record/migration.rb:587:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.1.4.4) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (6.1.4.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.1.4.4) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.1.4.4) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (6.1.4.4) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.1.4.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/static.rb:24:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/host_authorization.rb:119:in `call'
railties (6.1.4.4) lib/rails/engine.rb:539:in `call'
puma (5.5.2) lib/puma/configuration.rb:249:in `call'
puma (5.5.2) lib/puma/request.rb:77:in `block in handle_request'
puma (5.5.2) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
puma (5.5.2) lib/puma/request.rb:76:in `handle_request'
puma (5.5.2) lib/puma/server.rb:447:in `process_client'
puma (5.5.2) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
Started GET "/hello" for 127.0.0.1 at 2022-01-28 12:49:12 -0500
  
ActiveRecord::ConnectionNotEstablished (could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
):
  
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:83:in `rescue in new_client'
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:77:in `new_client'
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `public_send'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:926:in `checkout_new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:905:in `try_to_checkout_new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:866:in `acquire_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:588:in `checkout'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:428:in `connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:1128:in `retrieve_connection'
activerecord (6.1.4.4) lib/active_record/connection_handling.rb:327:in `retrieve_connection'
activerecord (6.1.4.4) lib/active_record/connection_handling.rb:283:in `connection'
activerecord (6.1.4.4) lib/active_record/migration.rb:611:in `connection'
activerecord (6.1.4.4) lib/active_record/migration.rb:606:in `build_watcher'
activerecord (6.1.4.4) lib/active_record/migration.rb:588:in `block in call'
activerecord (6.1.4.4) lib/active_record/migration.rb:587:in `synchronize'
activerecord (6.1.4.4) lib/active_record/migration.rb:587:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.1.4.4) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (6.1.4.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.1.4.4) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.1.4.4) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (6.1.4.4) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.1.4.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/static.rb:24:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/host_authorization.rb:119:in `call'
railties (6.1.4.4) lib/rails/engine.rb:539:in `call'
puma (5.5.2) lib/puma/configuration.rb:249:in `call'
puma (5.5.2) lib/puma/request.rb:77:in `block in handle_request'
puma (5.5.2) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
puma (5.5.2) lib/puma/request.rb:76:in `handle_request'
puma (5.5.2) lib/puma/server.rb:447:in `process_client'
puma (5.5.2) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
Started GET "/hello" for 127.0.0.1 at 2022-01-28 12:49:15 -0500
  
ActiveRecord::ConnectionNotEstablished (could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
):
  
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:83:in `rescue in new_client'
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:77:in `new_client'
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `public_send'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:926:in `checkout_new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:905:in `try_to_checkout_new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:866:in `acquire_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:588:in `checkout'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:428:in `connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:1128:in `retrieve_connection'
activerecord (6.1.4.4) lib/active_record/connection_handling.rb:327:in `retrieve_connection'
activerecord (6.1.4.4) lib/active_record/connection_handling.rb:283:in `connection'
activerecord (6.1.4.4) lib/active_record/migration.rb:611:in `connection'
activerecord (6.1.4.4) lib/active_record/migration.rb:606:in `build_watcher'
activerecord (6.1.4.4) lib/active_record/migration.rb:588:in `block in call'
activerecord (6.1.4.4) lib/active_record/migration.rb:587:in `synchronize'
activerecord (6.1.4.4) lib/active_record/migration.rb:587:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.1.4.4) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (6.1.4.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.1.4.4) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.1.4.4) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (6.1.4.4) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.1.4.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/static.rb:24:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/host_authorization.rb:119:in `call'
railties (6.1.4.4) lib/rails/engine.rb:539:in `call'
puma (5.5.2) lib/puma/configuration.rb:249:in `call'
puma (5.5.2) lib/puma/request.rb:77:in `block in handle_request'
puma (5.5.2) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
puma (5.5.2) lib/puma/request.rb:76:in `handle_request'
puma (5.5.2) lib/puma/server.rb:447:in `process_client'
puma (5.5.2) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
Started GET "/hello" for 127.0.0.1 at 2022-01-28 12:49:17 -0500
  
ActiveRecord::ConnectionNotEstablished (could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
):
  
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:83:in `rescue in new_client'
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:77:in `new_client'
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `public_send'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:926:in `checkout_new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:905:in `try_to_checkout_new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:866:in `acquire_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:588:in `checkout'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:428:in `connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:1128:in `retrieve_connection'
activerecord (6.1.4.4) lib/active_record/connection_handling.rb:327:in `retrieve_connection'
activerecord (6.1.4.4) lib/active_record/connection_handling.rb:283:in `connection'
activerecord (6.1.4.4) lib/active_record/migration.rb:611:in `connection'
activerecord (6.1.4.4) lib/active_record/migration.rb:606:in `build_watcher'
activerecord (6.1.4.4) lib/active_record/migration.rb:588:in `block in call'
activerecord (6.1.4.4) lib/active_record/migration.rb:587:in `synchronize'
activerecord (6.1.4.4) lib/active_record/migration.rb:587:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.1.4.4) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (6.1.4.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.1.4.4) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.1.4.4) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (6.1.4.4) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.1.4.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/static.rb:24:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/host_authorization.rb:119:in `call'
railties (6.1.4.4) lib/rails/engine.rb:539:in `call'
puma (5.5.2) lib/puma/configuration.rb:249:in `call'
puma (5.5.2) lib/puma/request.rb:77:in `block in handle_request'
puma (5.5.2) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
puma (5.5.2) lib/puma/request.rb:76:in `handle_request'
puma (5.5.2) lib/puma/server.rb:447:in `process_client'
puma (5.5.2) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
Started GET "/hello" for 127.0.0.1 at 2022-01-28 12:49:20 -0500
  
ActiveRecord::ConnectionNotEstablished (could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
):
  
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:83:in `rescue in new_client'
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:77:in `new_client'
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `public_send'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:926:in `checkout_new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:905:in `try_to_checkout_new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:866:in `acquire_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:588:in `checkout'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:428:in `connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:1128:in `retrieve_connection'
activerecord (6.1.4.4) lib/active_record/connection_handling.rb:327:in `retrieve_connection'
activerecord (6.1.4.4) lib/active_record/connection_handling.rb:283:in `connection'
activerecord (6.1.4.4) lib/active_record/migration.rb:611:in `connection'
activerecord (6.1.4.4) lib/active_record/migration.rb:606:in `build_watcher'
activerecord (6.1.4.4) lib/active_record/migration.rb:588:in `block in call'
activerecord (6.1.4.4) lib/active_record/migration.rb:587:in `synchronize'
activerecord (6.1.4.4) lib/active_record/migration.rb:587:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.1.4.4) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (6.1.4.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.1.4.4) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.1.4.4) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (6.1.4.4) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.1.4.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/static.rb:24:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/host_authorization.rb:119:in `call'
railties (6.1.4.4) lib/rails/engine.rb:539:in `call'
puma (5.5.2) lib/puma/configuration.rb:249:in `call'
puma (5.5.2) lib/puma/request.rb:77:in `block in handle_request'
puma (5.5.2) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
puma (5.5.2) lib/puma/request.rb:76:in `handle_request'
puma (5.5.2) lib/puma/server.rb:447:in `process_client'
puma (5.5.2) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
Started GET "/hello" for 127.0.0.1 at 2022-01-28 12:49:22 -0500
  
ActiveRecord::ConnectionNotEstablished (could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
):
  
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:83:in `rescue in new_client'
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:77:in `new_client'
activerecord (6.1.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `public_send'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:926:in `checkout_new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:905:in `try_to_checkout_new_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:866:in `acquire_connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:588:in `checkout'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:428:in `connection'
activerecord (6.1.4.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:1128:in `retrieve_connection'
activerecord (6.1.4.4) lib/active_record/connection_handling.rb:327:in `retrieve_connection'
activerecord (6.1.4.4) lib/active_record/connection_handling.rb:283:in `connection'
activerecord (6.1.4.4) lib/active_record/migration.rb:611:in `connection'
activerecord (6.1.4.4) lib/active_record/migration.rb:606:in `build_watcher'
activerecord (6.1.4.4) lib/active_record/migration.rb:588:in `block in call'
activerecord (6.1.4.4) lib/active_record/migration.rb:587:in `synchronize'
activerecord (6.1.4.4) lib/active_record/migration.rb:587:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.1.4.4) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (6.1.4.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.1.4.4) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.1.4.4) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (6.1.4.4) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (6.1.4.4) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.1.4.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/static.rb:24:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.1.4.4) lib/action_dispatch/middleware/host_authorization.rb:119:in `call'
railties (6.1.4.4) lib/rails/engine.rb:539:in `call'
puma (5.5.2) lib/puma/configuration.rb:249:in `call'
puma (5.5.2) lib/puma/request.rb:77:in `block in handle_request'
puma (5.5.2) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
puma (5.5.2) lib/puma/request.rb:76:in `handle_request'
puma (5.5.2) lib/puma/server.rb:447:in `process_client'
puma (5.5.2) lib/puma/thread_pool.rb:147:in `block in spawn_thread'
